spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/football
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  config: classpath:log4j2.yml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html